git:
  depth: 1
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
before_script:
  - npm install directory-tree remark remark-toc remark-html
script:
  - echo 'XD'
after_success:
  - git clone -b gh-pages https://github.com/CoderTonyChan/libpku.git
  - node index.js > libpku/index.html
  - cd libpku
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add .
  - git commit -m 'Add files via upload'
  - git push https://${DEPLOY_TOKEN}@github.com/CoderTonyChan/libpku.git gh-pages -f
